
project_id = "tqdoakirwvbyekhubwuz"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[functions.generate-template]
verify_jwt = true

[functions.create-stripe-customer]
verify_jwt = true

[functions.create-subscription]
verify_jwt = true

[functions.webhook-stripe]
verify_jwt = false
